#!/bin/bash

# Copyright © 2024 Pittsburgh Supercomputing Center.
# All Rights Reserved.

VERSION=7.3.0
PACKAGE=octave
TOOL=pandoc
DIRECTORY=$(dirname "$0")

STORAGES=(/ocean /bil /hive /local)

OPTIONS=""
for STORAGE in ""
do
        if [ -d "" ]; then
                OPTIONS=" -B "
        fi
done

if id | grep -q hubmap && [ -d "/hive" ]; then
        OPTIONS=" -B /hive"
fi

if id | grep -q bil && [ -d "/bil" ]; then
        OPTIONS=" -B /bil"
fi

singularity exec $OPTIONS $DIRECTORY/singularity-$PACKAGE-$VERSION.sif $TOOL "$@"
